package com.ioc.internship.entity;

public enum NotificationType {
    RENTAL_REQUEST_CREATED,
    RENTAL_REQUEST_APPROVED,
    RENTAL_REQUEST_REJECTED,
    PAYMENT_SUCCESS,
    RENTAL_HANDOVER_PENDING,
    RENTAL_RECEIVED,
    RENTAL_RETURN_PENDING,
    RENTAL_COMPLETED,
    REPORT_SUBMITTED_TO_ADMIN,
    REPORT_RESOLVED_FOR_REPORTER,
    REFUND_REQUIRED,
    REFUND_COMPLETED,
    REVIEW_RECEIVED
}
