services:
  postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: rental_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    deploy:
      resources:
        limits:
          memory: 512M

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: rental_pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      postgres:
        condition: service_healthy

  flyway:
    image: flyway/flyway:10-alpine
    container_name: rental_flyway
    # Mount thư mục chứa các file SQL từ máy vào bên trong container Flyway
    volumes:
      - ./backend/src/main/resources/db/migration:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_CONNECT_RETRIES=60
    # Flyway chỉ chạy sau khi Postgres "healthy"
    depends_on:
      postgres:
        condition: service_healthy
    # Lệnh Flyway tự động quét thư mục /flyway/sql và chạy migration
    command: -connectRetries=60 migrate

  maildev:
    image: maildev/maildev
    container_name: renthub-maildev
    ports:
      - "1025:1025" # Cổng để Spring Boot kết nối và bắn mail vào
      - "1080:1080" # Cổng mở trình duyệt (localhost:1080) xem hòm thư ảo

volumes:
  postgres_data:
  pgadmin_data:

